
####################################
#### Define notification types #####
####################################
services:
    phpbbgallery.core.notification.image_for_approval:
        class: phpbbgallery\core\notification\events\phpbbgallery_image_for_approval
        shared: false # scope MUST be prototype for this to work!
        parent: notification.type.base
        calls:
            - [set_user_loader, ['@user_loader']]
            - [set_config, ['@config']]
        tags:
            - { name: notification.type }
    phpbbgallery.core.notification.image_approved:
        class: phpbbgallery\core\notification\events\phpbbgallery_image_approved
        shared: false # scope MUST be prototype for this to work!
        parent: notification.type.base
        calls:
            - [set_user_loader, ['@user_loader']]
            - [set_config, ['@config']]
        tags:
            - { name: notification.type }
    phpbbgallery.core.notification.image_not_approved:
            class: phpbbgallery\core\notification\events\phpbbgallery_image_not_approved
            shared: false # scope MUST be prototype for this to work!
            parent: notification.type.base
            calls:
                - [set_user_loader, ['@user_loader']]
                - [set_config, ['@config']]
            tags:
                - { name: notification.type }
    phpbbgallery.core.notification.new_comment:
        class: phpbbgallery\core\notification\events\phpbbgallery_new_comment
        shared: false # scope MUST be prototype for this to work!
        parent: notification.type.base
        calls:
            - [set_user_loader, ['@user_loader']]
            - [set_config, ['@config']]
        tags:
            - { name: notification.type }
    phpbbgallery.core.notification.new_image:
        class: phpbbgallery\core\notification\events\phpbbgallery_new_image
        shared: false # scope MUST be prototype for this to work!
        parent: notification.type.base
        calls:
            - [set_user_loader, ['@user_loader']]
            - [set_config, ['@config']]
        tags:
            - { name: notification.type }
    phpbbgallery.core.notification.new_report:
        class: phpbbgallery\core\notification\events\phpbbgallery_new_report
        shared: false # scope MUST be prototype for this to work!
        parent: notification.type.base
        calls:
            - [set_user_loader, ['@user_loader']]
            - [set_config, ['@config']]
        tags:
            - { name: notification.type }
